# Generated by Django 5.0.12 on 2025-03-09 19:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_video_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-publish']},
        ),
        migrations.AddField(
            model_name='video',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='publish'),
        ),
        migrations.AddIndex(
            model_name='video',
            index=models.Index(fields=['-publish'], name='video_video_publish_88a488_idx'),
        ),
    ]
