[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"
watchPatterns = [
    "requirements.txt",
    "railway.toml",
    "Dockerfile",
    "playdeep/**",
    "app/**",
    "video/**"
]

[deploy]
healthcheckPath = "/admin/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"

[env]
GUNICORN_TIMEOUT = "300"
GUNICORN_WORKERS = "2"