# Generated by Django 5.0.12 on 2025-03-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0002_alter_video_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='slug',
            field=models.SlugField(default=1, max_length=250, unique_for_date='video'),
        ),
    ]
