# Generated by Django 5.1.7 on 2025-05-14 01:05

import django.db.models.deletion
import video.storage_backend
import video.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0005_alter_video_slug'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='video',
            field=models.FileField(storage=video.storage_backend.AzureMediaStorage, upload_to='%y/%m/%d', validators=[video.validators.file_size]),
        ),
    ]
